@startuml
object "AST" as 0 #666
object "FUNCTION" as 1 #666
0 -down-> 1
object "nope" as 2 #666
1 -down-> 2
object "FUNCDEF" as 3 #666
2 -down-> 3
object "COMMANDS" as 4 #666
3 -down-> 4
object "nop" as 5 #666
4 -down-> 5
object "ASSIGN" as 6 #666
4 -down-> 6
object "A" as 7 #666
6 -down-> 7
object "EXPRESSION" as 8 #666
6 -down-> 8
object "true" as 9 #666
8 -down-> 9
object "OUTPUT" as 10 #666
3 -down-> 10
object "A" as 11 #666
10 -down-> 11
@enduml